### ISSUE TITLE
INSTALL script error

### ISSUE THREAD

**Issue by bobberb** [daveajones/cartulary#13]
Would love to get this working, however, I encounter

`PHP Fatal error:  Call to a member function bind_param() on a non-object in /opt/cartulary/includes/admin.php on line 159`

from confcheck.php.

Mr. Jones, would you consider a docker image for this suite if it is so sensitive to OS versions?

**Comment by daveajones** [comment]
It can be installed on Ubuntu 12, 14 or 16.  I need to update the readme to reflect that.  I would be glad to do a docker image, but it would probably be multiple images since it's a LAMP app.

Here's a good video on how to do the server install:  https://www.youtube.com/watch?v=B39OVRWDR2E

I'll have to dig into this error and see what's going on.

**Comment by bobberb** [comment]
Was using digitalocean ubuntu 12. Will follow up after video.
